import Link from 'next/link';
import Image from 'next/image';

/**
 * The Legal Dash mark.
 *
 * The artwork is used exactly as supplied: navy and gold on a transparent
 * ground, with no plate, badge or circle behind it, so it sits on white, on a
 * tinted panel or on paper without being redrawn or boxed in. `logo.svg` is a
 * traced vector version of the same artwork, generated by
 * `tools/brand/make_logo.py`, so the mark stays sharp at any size — in the
 * header, in print, and on a receipt.
 */
const MARK_RATIO = 428 / 533;

export function LogoMark({
  size = 32,
  className,
  title,
}: {
  /** Height in pixels. The width follows the artwork's proportions. */
  size?: number;
  className?: string;
  /** A label for the mark when it stands alone; omit it where the text beside it says the same thing. */
  title?: string;
}) {
  return (
    <Image
      src="/logo.svg"
      alt={title ?? ''}
      aria-hidden={title ? undefined : true}
      width={Math.round(size * MARK_RATIO)}
      height={size}
      unoptimized
      className={className}
      style={{ height: size, width: 'auto' }}
    />
  );
}

export function Wordmark({ className }: { className?: string }) {
  return (
    <span className={className ?? 'text-base font-semibold tracking-tight text-slate-900'}>
      Legal{' '}<span className="text-brand-700">Dash</span>
    </span>
  );
}

/** The mark with the product name beside it — the header and footer lockup. */
export function Logo({
  compact = false,
  href = '/',
  size = 32,
}: {
  compact?: boolean;
  href?: string;
  size?: number;
}) {
  return (
    <Link
      href={href}
      className="inline-flex items-center gap-2.5"
      aria-label="Legal Dash — home"
    >
      <LogoMark size={size} />
      {!compact ? <Wordmark /> : null}
    </Link>
  );
}
