import Link from 'next/link';
import Image from 'next/image';

/**
 * The Dubai Legal mark.
 *
 * The artwork is used exactly as supplied: navy and gold on a transparent
 * ground, with no plate, badge or circle behind it, so it sits on white, on a
 * tinted panel or on paper without being redrawn or boxed in. `logo.svg` is a
 * traced vector version of the same artwork, generated by
 * `tools/brand/make_logo.py`, so the mark stays sharp at any size — in the
 * header, in print, and on a receipt.
 */
const MARK_RATIO = 428 / 533;

export function LogoMark({
  size = 32,
  className,
  title,
}: {
  /** Height in pixels. The width follows the artwork's proportions. */
  size?: number;
  className?: string;
  /** A label for the mark when it stands alone; omit it where the text beside it says the same thing. */
  title?: string;
}) {
  return (
    <Image
      src="/logo.svg"
      alt={title ?? ''}
      aria-hidden={title ? undefined : true}
      width={Math.round(size * MARK_RATIO)}
      height={size}
      unoptimized
      className={className}
      style={{ height: size, width: 'auto' }}
    />
  );
}

export function Wordmark({ className }: { className?: string }) {
  return (
    <span className={className ?? 'text-base font-semibold tracking-tight text-slate-900'}>
      Dubai<span className="text-brand-700">Legal</span>
    </span>
  );
}

/** The mark with the product name beside it — the header and footer lockup. */
export function Logo({
  compact = false,
  href = '/',
  size = 32,
}: {
  compact?: boolean;
  href?: string;
  size?: number;
}) {
  return (
    <Link
      href={href}
      className="inline-flex items-center gap-2.5"
      aria-label="Dubai Legal — home"
    >
      <LogoMark size={size} />
      {!compact ? <Wordmark /> : null}
    </Link>
  );
}

/**
 * The full lockup, for a document rather than a page: the mark, the name, and
 * the line that says what this is. Used on receipts and on anything the browser
 * prints.
 */
export function BrandLockup({
  className,
  markSize = 44,
  invert = false,
}: {
  className?: string;
  markSize?: number;
  /** White text, for a dark surface. The mark itself is unchanged. */
  invert?: boolean;
}) {
  return (
    <div className={className ?? 'flex items-center gap-3'}>
      <LogoMark size={markSize} />
      <div className="min-w-0">
        <p className={invert ? 'font-semibold text-white' : 'font-semibold text-slate-900'}>
          Dubai Legal
        </p>
        <p className={invert ? 'text-xs text-brand-100' : 'text-xs text-slate-500'}>
          Lawyers and legal firms of the United Arab Emirates
        </p>
      </div>
    </div>
  );
}

/**
 * The brand on anything printed.
 *
 * Laid out in the print stylesheet above the page content, and hidden on screen.
 * A page printed from this application — a case, a receipt, a meeting — should
 * come off the printer on letterhead, not as a loose sheet of text.
 */
export function PrintBrand({ context }: { context?: string }) {
  return (
    <div className="mb-6 hidden items-center justify-between border-b border-slate-300 pb-3 print:flex">
      <BrandLockup markSize={40} />
      {context ? <p className="text-xs text-slate-500">{context}</p> : null}
    </div>
  );
}
